# Add 'webapp' label to any change within the 'webapp' directory
webapp:
  - changed-files:
      - any-glob-to-any-file: ["webapp/**"]

# Add 'webapi' label to any change within the 'webapi' directory
webapi:
  - changed-files:
      - any-glob-to-any-file: ["webapi/**"]

# Add 'dataapi' label to any change within the 'dataapi' directory
dataapi:
  - changed-files:
      - any-glob-to-any-file: ["dataapi/**"]

# Add 'dependencies' label to any change of the 'webapp/yarn.lock' file
dependencies:
  - changed-files:
      - any-glob-to-any-file: ["webapp/yarn.lock"]

# Add 'deployment' label to any change within the 'deploy' directory
deployment:
  - changed-files:
      - any-glob-to-any-file: ["scripts/deploy/**"]

# Add 'documentation' label to any change of '.md' files
documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

# Add 'github actions' label to any change within the '.github/workflows' directory
"github actions":
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**"]
